### ISSUE TITLE
not able to run example program main.go

### ISSUE THREAD

**Issue by surajssd** [docker/libcompose#261]
Trying to run https://github.com/docker/libcompose/blob/master/example/main.go and getting error as:

```bash
$ go run main.go 
# command-line-arguments
./main.go:22: not enough arguments in call to project.Up
```
on compose file

```yaml
$ cat docker-compose.yml 
postgresql:
  image: swordphilic/postgresql
  ports:
    - "5432"
  environment:
    DB_NAME: gitlab
    DB_PASS: gitlab
    DB_USER: gitlab

gitlab:
  image: swordphilic/gitlab
  ports:
    - "30000:80"
    - "30001:443"
    - "30002:22"
  links:
    - redis
    - postgresql
  environment:
    DB_TYPE: postgres
    DB_NAME: gitlab
    DB_PASS: gitlab
    DB_USER: gitlab

redis:
  image: swordphilic/redis
  ports:
    - "6379"
```
