### ISSUE TITLE
unmarshall error when environment variable given as int

### ISSUE THREAD

**Issue by surajssd** [docker/libcompose#266]
I am tryig out libcompose using a docker-compose.yml file as shown below, the application works fine when running using `docker-compose up` with the same compose file. But when using libcompose I get error as: `ERRO[0000] Failed to unmarshall: Cannot unmarshal '6379' of type int64 into a string value`

#### Software Versions:

```bash
$ go version
go version go1.6.2 linux/amd64

$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

docker-compose.yml
```yaml
$ cat docker-compose.yml 
version: "2"

services:
  postgresql:
    image: swordphilic/postgresql
    ports:
      - "5432"
    environment:
      DB_NAME: gitlab
      DB_PASS: gitlab
      DB_USER: gitlab

  gitlab:
    image: swordphilic/gitlab
    ports:
      - "30000:80"
      - "30001:443"
      - "30002:22"
    restart: always
    environment:
      DB_TYPE: postgres
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_NAME: gitlab
      DB_PASS: gitlab
      DB_USER: gitlab
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: swordphilic/redis
    ports:
      - "6379"
```

And the source code that I am running is the example code which is in PR stage right now: https://github.com/docker/libcompose/pull/265

Detailed error:

```bash
$ go run main.go 
ERRO[0000] Failed to unmarshall: Cannot unmarshal '6379' of type int64 into a string value
gitlab:
  environment:
    DB_HOST: postgresql
    DB_NAME: gitlab
    DB_PASS: gitlab
    DB_PORT: 5432
    DB_TYPE: postgres
    DB_USER: gitlab
    REDIS_HOST: redis
    REDIS_PORT: 6379
  image: swordphilic/gitlab
  ports:
  - 30000:80
  - 30001:443
  - 30002:22
  restart: always
postgresql:
  environment:
    DB_NAME: gitlab
    DB_PASS: gitlab
    DB_USER: gitlab
  image: swordphilic/postgresql
  ports:
  - "5432"
redis:
  image: swordphilic/redis
  ports:
  - "6379"
 
ERRO[0000] Could not parse config for project yeahcompose : Cannot unmarshal '6379' of type int64 into a string value 
2016/05/18 00:17:12 Cannot unmarshal '6379' of type int64 into a string value
exit status 1
```

But when I make change to environment variables `DB_PORT: 5432` to `DB_PORT: "5432"` and `REDIS_PORT: 6379` to `REDIS_PORT: "6379"` this works fine and also `docker-compose up` works fine. But I would like to have this work with integer form of environment variable.
