### ISSUE TITLE
 'libcompose-cli up' creates project with undefined links

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/libcompose#288]
With reference to docker compose file as below.

``` yaml
web:
  image: ubuntu
  links:
   - redis
   - kk
redis:
  image: redis
```

``libcompose-cli up`` should fail, as ``kk`` is undefined. But it creates the project.

This behaviour is not similar to ``docker-compose`` which prints error and stop.
