### ISSUE TITLE
build: path not supported

### ISSUE THREAD

**Issue by bodymindarts** [docker/libcompose#291]
```yaml
version: '2'
services:
  app:
    build: app
    image: app
```

won't parse correctly due to [this line](https://github.com/docker/libcompose/blob/master/config/merge_v2.go#L189) even though it is correct v2 [syntax](https://docs.docker.com/compose/compose-file/#build)
