### ISSUE TITLE
Environment variables specified as dictionary keys w/o value get set to <nil>

### ISSUE THREAD

**Issue by janeczku** [docker/libcompose#296]
docker-compose.yml:

```YAML
testing:
  image: ubuntu:14.04
  environment:
    FOO:
```

> $ FOO=BAR rancher-compose up

Result:

```YAML
testing:
  environment:
    FOO: <nil>
  image: ubuntu:14.04
```

> $ FOO=BAR libcompose-cli up

Result:

```YAML
ERRO[0000] Failed to unmarshall: Cannot unmarshal '<nil>' of type <nil> into a string value
testing:
  environment:
    FOO: null
  image: ubuntu:14.04
```

Expected:

Environment variables with only a key are resolved to their values on the machine Compose is running on (https://docs.docker.com/compose/compose-file/#environment)
