### ISSUE TITLE
Building from compose file does not match behavior of docker-compose

### ISSUE THREAD

**Issue by dansteen** [docker/libcompose#311]
Hey!

I noticed the following comment in docker/service.go:

```
// Build implements Service.Build. If an imageName is specified or if the context has
// no build to work with it will do nothing. Otherwise it will try to build
// the image and returns an error if any.
func (s *Service) Build(ctx context.Context, buildOptions options.Build) error {
...
```

This does not seem to match the behavior of docker-compose which says here https://docs.docker.com/compose/compose-file/#image:

```
**Image**
Specify the image to start the container from. Can either be a repository/tag or a partial image ID.
If the image does not exist, Compose attempts to pull it, unless you have also specified build, in which case it builds it using the specified options and tags it with the specified tag.
```

Is it possible to get this behavior in libcompose as well?

Thanks!
Dan

**Comment by dansteen** [comment]
Turns out the code for this is mostly already in, it's just explicitly disabled.   Once I removed the explicit disable there seems to be some strange race condition (or map ordering thing?) where sometimes it will complete the build and sometimes it won't.  It seems to hinge on whether it populates Service.Config().Build or not.  I'm looking into it.

**Comment by dansteen** [comment]
Ok. I figured it out.  docker-compose will print a message and skip service specifications that do not include a "build" section, while libcompose prints a message and fails.   So, given a config file like this:

```
services:
  org-api-test.migrate.tmp:
    image: org-api:build
  org-api.migrate.tmp:
    image: org-api:build

  org-api.app.local:
    image: org-api:testbob
    build:
      context: .
      args:
        - VAULT_TOKEN
        - APP_VERSION
```
docker-compose will print ```org-api-test.migrate.tmp uses an image, skipping``` and move on to the next service.  While libcompose will print ```Specified service does not have a build section``` and fail.  I'll adjust this in the PR as well.
