### ISSUE TITLE
build args don't get populated

### ISSUE THREAD

**Issue by dansteen** [docker/libcompose#312]
Hey!

Thanks so much for your work on this!  I noticed that given the following config:
```
version: '2'
services:
  org-api.app.local:
    build:
      context: .
      args:
        - VAULT_TOKEN
        - APP_VERSION
```

The build args don't get populated into the Service config.  This works in docker-compose, and it reads the values of those args from ENV variables per  https://docs.docker.com/compose/compose-file/#args:
```
Build arguments with only a key are resolved to their environment value on the machine Compose is running on.

```

I did notice that if I changed it to this:
```
version: '2'
services:
  org-api.app.local:
    build:
      context: .
      args:
        VAULT_TOKEN: bob
        APP_VERSION: dave
```

Then it would pass those values into the Service config, but it would not set the corresponding args in the actual Docker build.  I'm not sure if it makes a difference, but in the Dockerfile, all the args have default values set.

I did find this: https://github.com/docker/libcompose/pull/307 which seems like it would be relevant, but for environments rather than args.

Thanks!
