### ISSUE TITLE
Strict yaml validation?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/libcompose#34]
I have mistakes in my docker-compose.yml file such as mistyped keys (`fooooocommand`):

```yml
consul:
  fooooocommand: -server -node master2 -advertise 10.0.0.6 -join 10.0.0.4 -join 10.0.0.5
  image: progrium/consul
  ports:
  - 8300:8300
```

libcompose seems to be ignoring them, however docker-compose does strict validation and errors out. We probably need the same behavior here.
