### ISSUE TITLE
Volumes are not being prefixed with ProjectName

### ISSUE THREAD

**Issue by james-fitzgerald** [docker/libcompose#348]
I have a docker-compose file that includes a 'volumes' entry at the top level and a number of services. When I create the project passing in ProjectName in the context the services are correctly prefixed with the ProjectName however the volume is not.  This causes problems when mixing use of the libcompose with the docker-compose command line.

Did my best to extract the relevant code to show how I am using it. Hopefully the description above is clear enough.

```
version: '2'

services:
 pg:
    image: XXXX
    volumes:
      - pg_datum:/var/lib/postgresql/data
volumes:
  pg_datum: {}
````

```
 myProject, err := docker.NewProject(
		&docker.Context{
			Context: project.Context{
				ComposeFiles: []string{"../docker-compose.yml", "../docker-compose.override.yml"},
				ProjectName:  "superproject",
			},
		},
	nil,
	)	
err = myProject.Up(context.Background(), options.Up{})
```
