### ISSUE TITLE
Inaccurate service name in the logs

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/libcompose#35]
This yml file:

```yml
sleep1:
  command: sleep 8888888
  image: busybox
  restart: always
sleep2:
  command: sleep 9999999
  image: busybox
  restart: always
```

results in the following logs (from the `example/main.go`):

```
INFO[0000] [0/2] [sleep1]: Starting
INFO[0000] [1/2] [sleep1]: Started
```

note that there are two `sleep1`s. However `docker ps` shows that sleep1 and sleep2 is created successfully...

So if I add another `sleep3`

```yml
sleep1:
  command: sleep 8888888
  image: busybox
  restart: always
sleep2:
  command: sleep 9999999
  image: busybox
  restart: always
sleep3:
  command: sleep 7777777
  image: busybox
  restart: always
```

it works fine:

```
INFO[0000] [0/3] [sleep1]: Starting
INFO[0001] [1/3] [sleep2]: Started
INFO[0001] [2/3] [sleep3]: Started
```

I'm guessing there's something wrong with the logs.
