### ISSUE TITLE
Volumes are not mounted correctly on the container

### ISSUE THREAD

**Issue by kuma-giyomu** [docker/libcompose#42]
On Windows if you have a simple data container

```
data:
  image: busybox
  volumes:
    - /data
    - /var/lib/mysql
```

The filesystem of the container will show it mounted the following (`ls -l /`)

```
\data
\var\lib\mysql
```
Applying the windows slash pattern results in unusable volumes.
