### ISSUE TITLE
Suffixes not allowed for docker-compose.yml

### ISSUE THREAD

**Issue by tiffanyfj** [docker/libcompose#425]
Created to address https://github.com/aws/amazon-ecs-cli/issues/1

docker-compose.yml
```
web:
    image: nginx
    ports: 
        - "80:80"
    mem_limit: 50M
```

```
ERRO[0000] Failed to unmarshall: strconv.ParseInt: parsing "50M": invalid syntax
web:
  image: nginx
  mem_limit: 50M
  ports:
  - 80:80
```

Fix:
Change 
```
intType, err := strconv.ParseInt(stringType, 10, 64)
```
to 
```
if stringType == "" {
	return errors.New("Unmarshalled string is empty. Failed to convert to IntType")
}
intType, err := units.RAMInBytes(stringType
```
