### ISSUE TITLE
serviceConfig.Environment.ToMap() doesn't support environment variables containing equals signs ("=")

### ISSUE THREAD

**Issue by jritsema** [docker/libcompose#454]
Similar to [this issue](https://github.com/docker/libcompose/pull/87), the `Environment.ToMap()` [API](https://github.com/docker/libcompose/blob/master/yaml/types_yaml.go#L153) isn't able to parse equals signs (`=`).  For example:

```
version: "2"
services:
  container:
    image: helloworld
    environment:
      CHAR_EQUAL: =foo=bar=
```

```
serviceConfig, success := project.GetServiceConfig("container")
if !success {
  log.Fatal("fail")
}
for key, value := range serviceConfig.Environment.ToMap() {
  //value is empty
  log.Printf("%v = %v", key, value)
}
```
