### ISSUE TITLE
Issue with env_file population.

### ISSUE THREAD

**Issue by cdrage** [docker/libcompose#488]
Using this an example:

```
version: '2'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    env_file:
      - foo.env
      - bar.env
    ports:
      - '6379:6379'
```

It seems that `env_file` isn't being properly populated to the ServiceConfig.

It's hard to explain without showing code, but essentially we use libcompose to parse a Docker Compose file and `env_file` within ServiceConfig is blank. 

Yes, it goes through the file and grabs the environment variables correctly, but within the libcompose code, `env_file` isn't being shown within ServiceConfig (appears as a blank string).

I'll try to pull up an example later :+1:
